# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Renuo Internet Solutions
email: info@renuo.ch
description: >
  Die Renuo GmbH ist Spezialist in den Bereichen individuelle Webentwicklung, mobile Applikationen,
  responsive Design und Content Management.
keywords: >
  Renuo, Internet soulutions, Web, Websites, Webseite, Internet Seite, Internetseite, Homepage, Homepages, Consulting,
  Software Engineering, Ruby, Ruby on Rails, mobile, mobile apps, JavaScript, nodejs, node, android, ipad, iphone,
  rails, professional, Webagentur, Websiten, Web 2.0, CMS, Web-Applikationen, E-Commerce Lösungen
author: Renuo GmbH | info@renuo.ch | http://www.renuo.ch
baseurl: ''
url: 'https://www.renuo.ch'
twitter_username: renuo
github_username: renuo

# Build settings
markdown: kramdown
