# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Renuo Internet Solutions
email: info@renuo.ch
description: >
  Renuo AG, Internet solutions
baseurl: ''
url: 'https://www.renuo.ch'
twitter_username: renuo
github_username: renuo

# Build settings
markdown: kramdown
